name = "Villain"
license = "MIT"
licenselink = "https://github.com/luciorq/hugo-villain-theme/blob/master/LICENSE.md"
description = "Villain is a multipurpose theme with fullscreen hero images and fullwidth sections. It contains content types for a business or portfolio site."
homepage = "https://github.com/luciorq/hugo-villain-theme"
tags = ["responsive","minimal","clean","company","portfolio","bootstrap"]
features = ["services","work","fullwidth","hero images"]
min_version = "0.74.3"

[author]
  name = "Lucio Rezende Queiroz"
  homepage = "https://github.com/luciorq"

# If porting an existing theme
[original]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"
  repo = "https://github.com/zerostaticthemes/hugo-hero-theme"

