baseURL = "https://luciorq.github.io/hugo-villain-theme"
# baseURL = "www.example.com"
languageCode = "en-us"
title = "Hugo Villain Theme"
themesDir = "../.."
theme = "hugo-villain-theme"

publishDir = "../docs"


[params]
  google_analytics_id=""

  [params.colors]
    background_color = "#eff4ef"
    black = "#8a7a50"
    primary_color = "#37505a"
    secondary_color = "#83a0a6"

  [params.homepage_meta_tags]
    meta_description = "A modern villainous approach on the hero theme for Hugo."
    meta_og_title = "Hugo Villain Theme"
    meta_og_type = "website"
    meta_og_url = "http://luciorq.github.io/hugo-villain-theme"
    meta_og_image = "https://raw.githubusercontent.com/luciorq/hugo-villain-theme/master/images/tn.png"
    meta_og_description = "A modern villainous approach on the hero theme for Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@luciorqueiroz"
    meta_twitter_creator = "@luciorqueiroz"

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 1

[[menu.main]]
  name = "Work"
  url = "/work/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "History"
  url = "/history/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"


# necessary for Rmarkdown integration with GitHub Pages
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
